-- Creacion de base de datos
CREATE DATABASE pokemon;

-- Ahora debe de seleccionar la base de datos de Pokemon para agregar las listas y los datos

-- Tabla ENTRENADOR
CREATE TABLE ENTRENADOR (
    ID_ENTRENADOR INT PRIMARY KEY,
    USUARIO VARCHAR(20) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(20) NOT NULL,
    POKEDOLARES INT DEFAULT 1000
);

-- Tabla OBJETO
CREATE TABLE OBJETO (
    ID_OBJETO INT PRIMARY KEY,
    NOM_OBJETO VARCHAR(50) NOT NULL,
    ATAQUE INT,
    DEFENSA INT,
    AT_ESPECIAL INT,
    DEF_ESPECIAL INT,
    VELOCIDAD INT,
    VITALIDAD INT,
    PP INT,
    PRECIO INT NOT NULL
);

-- Tabla MOCHILA
CREATE TABLE MOCHILA (
    ID_ENTRENADOR INT,
    ID_OBJETO INT,
    CANTIDAD INT NOT NULL,
    PRIMARY KEY (ID_ENTRENADOR, ID_OBJETO),
    FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID_ENTRENADOR),
    FOREIGN KEY (ID_OBJETO) REFERENCES OBJETO(ID_OBJETO)
);

-- Tabla POKEDEX
CREATE TABLE POKEDEX (
    NUM_POKEDEX INT PRIMARY KEY,
    NOM_POKEMON VARCHAR(20) NOT NULL,
    IMG_FRONTAL VARCHAR(50),
    IMG_TRASERA VARCHAR(50),
    SPRITES_FRONTAL VARCHAR(50),
    SPRITES_TRASEROS VARCHAR(50),
    SONIDO VARCHAR(100),
    NIVEL_EVOLUCION INT,
    TIPO1 VARCHAR(20) NOT NULL CHECK (TIPO1 IN('AGUA', 'BICHO','DRAGON','ELECTRICO','FANTASMA','FUEGO','HIELO','LUCHA','NORMAL','PLANTA','PSIQUICO','ROCA','TIERRA','VENENO','VOLADOR')),
    TIPO2 VARCHAR(20)
);

-- Tabla POKEMON
CREATE TABLE POKEMON (
    ID_POKEMON INT PRIMARY KEY,
    ID_ENTRENADOR INT,
    NUM_POKEDEX INT,
    ID_OBJETO INT NULL,
    NOM_POKEMON VARCHAR(20) NOT NULL,
    VITALIDAD INT NOT NULL,
    ATAQUE INT NOT NULL,
    DEFENSA INT NOT NULL,
    AT_ESPECIAL INT NOT NULL,
    DEF_ESPECIAL INT NOT NULL,
    VELOCIDAD INT NOT NULL,
    NIVEL INT NOT NULL,
    FERTILIDAD INT NOT NULL DEFAULT 5,
    SEXO CHAR(1) NOT NULL CHECK (SEXO IN ('M', 'X')),
    ESTADO VARCHAR(30) NOT NULL CHECK (ESTADO IN ('NORMAL', 'PARALIZADO', 'QUEMADO', 'ENVENENADO', 'GRAVEMENTE ENVENENADO', 'DORMIDO', 'CONGELADO', 'HELADO', 'SOMNOLIENTO', 'POKERUS', 'DEBILITADO', 'CONFUSO', 'ENAMORADO', 'ATRAPADO', 'MALDITO', 'DRENADORAS', 'CANTO MORTAL', 'CENTRO DE ATENCION', 'AMEDRENTADO')),
    EQUIPO INT NOT NULL CHECK (EQUIPO IN (1, 2, 3)),
    FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID_ENTRENADOR),
    FOREIGN KEY (NUM_POKEDEX) REFERENCES POKEDEX(NUM_POKEDEX),
    FOREIGN KEY (ID_OBJETO) REFERENCES OBJETO(ID_OBJETO) ON DELETE SET NULL
);

-- Tabla MOVIMIENTO
CREATE TABLE MOVIMIENTO(
    ID_MOVIMIENTO INT PRIMARY KEY,
    NOM_MOVIMIENTO VARCHAR(20) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRECI INT(3) NOT NULL,
    PP_MAX INT(2) NOT NULL,
    TIPO VARCHAR(20) CHECK (TIPO IN('ATAQUE', 'ESTADO','MEJORA')),
    TIPO_MOV VARCHAR(30) CHECK (TIPO_MOV IN('AGUA','BICHO','DRAGON','ELECTRICO','FANTASMA','FUEGO','HIELO','LUCHA','NORMAL','PLANTA','PSIQUICO','ROCA','TIERRA','VENENO','VOLADOR')),
    -- ATAQUE
    POTENCIA INT,
    -- ESTADO
    ESTADO VARCHAR(30) CHECK (ESTADO IN ('NORMAL', 'PARALIZADO', 'QUEMADO', 'ENVENENADO', 'GRAVEMENTE ENVENENADO', 'DORMIDO', 'CONGELADO', 'HELADO', 'SOMNOLIENTO', 'POKERUS', 'DEBILITADO', 'CONFUSO', 'ENAMORADO', 'ATRAPADO', 'MALDITO', 'DRENADORAS', 'CANTO MORTAL', 'CENTRO DE ATENCION', 'AMEDRENTADO')),
    TURNOS INT(1),
    -- MEJORA
    MEJORA VARCHAR(20),
    NUM_MOV INT(1) NOT NULL, -- Todos los movimientos tienen que tener al menos 1 (que es lo que dura)
    CANT_MEJORA INT(3)
);

-- Tabla MOVIMIENTO_POKEMON
CREATE TABLE MOVIMIENTO_POKEMON (
    ID_ENTRENADOR INT,
    ID_MOVIMIENTO INT,
    PP_ACTUALES INT,
    PRIMARY KEY (ID_ENTRENADOR, ID_MOVIMIENTO),
    FOREIGN KEY (ID_ENTRENADOR) REFERENCES ENTRENADOR(ID_ENTRENADOR),
    FOREIGN KEY (ID_MOVIMIENTO) REFERENCES MOVIMIENTO(ID_MOVIMIENTO)
);


INSERT INTO MOVIMIENTO (ID_MOVIMIENTO, NOM_MOVIMIENTO, DESCRIPCION, PRECI, PP_MAX, TIPO, TIPO_MOV, POTENCIA, ESTADO, TURNOS, MEJORA, NUM_MOV, CANT_MEJORA) VALUES 
(0001, 'Destructor', 'Golpea al objetivo con las extremidades, la cola o similares.', 100, 35, 'ATAQUE', 'NORMAL', 40, NULL, 1, NULL, 0, NULL),
(0002, 'Golpe Karate', 'Da un golpe cortante. Suele ser crítico.', 100, 25, 'ATAQUE', 'LUCHA', 50, NULL, 1, NULL, 0, NULL),
(0003, 'Doble Bofetón', 'Abofetea de dos a cinco veces seguidas.', 85, 15, 'ATAQUE', 'NORMAL', 15, NULL, 1, NULL, 0, NULL),
(0004, 'Puño Cometa', 'Pega de dos a cinco veces seguidas.', 85, 15, 'ATAQUE', 'NORMAL', 18, NULL, 1, NULL, 0, NULL),
(0005, 'Megapuño', 'Puñetazo de gran potencia.', 85, 20, 'ATAQUE', 'NORMAL', 80, NULL, 1, NULL, 0, NULL),
(0006, 'Día de Pago', 'Ataca al objetivo arrojándole monedas. Al finalizar el combate, las recupera en forma de ganancias.', 100, 20, 'ATAQUE', 'NORMAL', 40, NULL, 1, NULL, 0, NULL),
(0007, 'Puño Fuego', 'Puñetazo ardiente que puede causar quemaduras.', 100, 15, 'ATAQUE', 'FUEGO', 75, NULL, 1, NULL, 0, NULL),
(0008, 'Puño Hielo', 'Puñetazo helado que puede llegar a congelar.', 100, 15, 'ATAQUE', 'HIELO', 75, NULL, 1, NULL, 0, NULL),
(0009, 'Puño Trueno', 'Puñetazo eléctrico que puede paralizar.', 100, 15, 'ATAQUE', 'ELECTRICO', 75, NULL, 1, NULL, 0, NULL),
(0010, 'Arañazo', 'Araña con afiladas garras.', 100, 35, 'ATAQUE', 'NORMAL', 40, NULL, 1, NULL, 0, NULL),
(0011, 'Agarre', 'Atenaza al objetivo y le inflige daño.', 100, 30, 'ATAQUE', 'NORMAL', 55, NULL, 1, NULL, 0, NULL),
(0012, 'Guillotina', 'Ataque cortante con grandes pinzas que fulmina al objetivo de un solo golpe si acierta.', 30, 5, 'ATAQUE', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0013, 'Viento Cortante', 'Primero se prepara y en el segundo turno ataca al oponente con ráfagas de viento cortante. Alta probabilidad de ser crítico.', 100, 10, 'ATAQUE', 'NORMAL', 80, NULL, 2, NULL, 0, NULL),
(0014, 'Danza Espada', 'Este frenético baile de combate eleva el espíritu y aumenta mucho el Ataque.', 100, 30, 'MEJORA', 'NORMAL', 0, NULL, 1, 'ATAQUE+', 0, 2),
(0015, 'Corte', 'Corta al objetivo con garras, guadañas o similares.', 95, 30, 'ATAQUE', 'NORMAL', 50, NULL, 1, NULL, 0, NULL),
(0016, 'Tornado', 'Crea un tornado con las alas y lo lanza contra el objetivo.', 100, 35, 'ATAQUE', 'VOLADOR', 40, NULL, 1, NULL, 0, NULL),
(0017, 'Ataque Ala', 'Extiende totalmente sus majestuosas alas para golpear al objetivo con ellas.', 100, 35, 'ATAQUE', 'VOLADOR', 60, NULL, 1, NULL, 0, NULL),
(0018, 'Remolino', 'Se lleva al objetivo, que es cambiado por otro Pokémon. Si es un Pokémon salvaje, acaba el combate.', 85, 20, 'ESTADO', 'NORMAL', 0, 'ATRAPADO', 1, NULL, 0, NULL),
(0019, 'Vuelo', 'El usuario vuela en el primer turno y ataca en el segundo.', 95, 15, 'ATAQUE', 'VOLADOR', 90, NULL, 2, NULL, 0, NULL),
(0020, 'Atadura', 'Usa el cuerpo o las extremidades para atar y oprimir al objetivo e infligirle daño de cuatro a cinco turnos.', 85, 20, 'ATAQUE', 'NORMAL', 15, 'ATRAPADO', 4, NULL, 0, NULL),
(0021, 'Latigazo', 'Golpea con la cola o con lianas, por ejemplo, para causar daño al objetivo.', 75, 20, 'ATAQUE', 'NORMAL', 80, NULL, 1, NULL, 0, NULL),
(0022, 'Látigo Cepa', 'Azota al objetivo con lianas delgadas y largas tan flexibles como látigos.', 100, 25, 'ATAQUE', 'PLANTA', 45, NULL, 1, NULL, 0, NULL),
(0023, 'Pisotón', 'Tremendo pisotón que puede hacer que el objetivo se amedrente.', 100, 20, 'ATAQUE', 'NORMAL', 65, 'AMEDRENTADO', 1, NULL, 0, NULL),
(0024, 'Doble Patada', 'Propina dos patadas seguidas, una con cada pie.', 100, 30, 'ATAQUE', 'LUCHA', 30, NULL, 1, NULL, 0, NULL),
(0025, 'Megapatada', 'Patada de extrema fuerza.', 75, 5, 'ATAQUE', 'NORMAL', 120, NULL, 1, NULL, 0, NULL),
(0026, 'Patada Salto', 'Da un salto y pega una patada. Si falla, se lesiona.', 95, 10, 'ATAQUE', 'LUCHA', 100, NULL, 1, NULL, 0, NULL),
(0027, 'Patada Giro', 'Da una patada rápida y circular. Puede hacer retroceder al objetivo.', 85, 15, 'ATAQUE', 'LUCHA', 60, NULL, 1, NULL, 0, NULL),
(0028, 'Ataque Arena', 'Arroja arena a la cara del objetivo y reduce su Precisión.', 100, 15, 'ESTADO', 'NORMAL', 0, NULL, 1, 'PRECISION-', 0, 1),
(0029, 'Golpe Cabeza', 'Potente cabezazo que puede amedrentar al objetivo.', 100, 15, 'ATAQUE', 'NORMAL', 70, 'AMEDRENTADO', 1, NULL, 0, NULL),
(0030, 'Cornada', 'Ataca al objetivo con una cornada punzante.', 100, 25, 'ATAQUE', 'NORMAL', 65, NULL, 1, NULL, 0, NULL),
(0031, 'Ataque Furia', 'Cornea o picotea al objetivo de dos a cinco veces seguidas.', 85, 20, 'ATAQUE', 'NORMAL', 15, NULL, 1, NULL, 0, NULL),
(0032, 'Perforador', 'Ataque con un cuerno giratorio que fulmina al objetivo de un solo golpe si acierta.', 30, 5, 'ATAQUE', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0033, 'Placaje', 'Embestida con todo el cuerpo.', 100, 35, 'ATAQUE', 'NORMAL', 40, NULL, 1, NULL, 0, NULL),
(0034, 'Golpe Cuerpo', 'Salta sobre el objetivo con todo su peso y puede llegar a paralizarlo.', 100, 15, 'ATAQUE', 'NORMAL', 85, 'PARALIZADO', 1, NULL, 0, NULL),
(0035, 'Constricción', 'Oprime al objetivo de cuatro a cinco turnos con lianas o con su cuerpo.', 90, 20, 'ATAQUE', 'NORMAL', 15, 'ATRAPADO', 4, NULL, 0, NULL),
(0036, 'Derribo', 'Carga desmedida que también hiere ligeramente al usuario.', 85, 20, 'ATAQUE', 'NORMAL', 90, NULL, 1, NULL, 0, NULL),
(0037, 'Saña', 'El usuario ataca enfurecido durante dos o tres turnos y, después, se queda confuso.', 100, 10, 'ATAQUE', 'NORMAL', 120, 'CONFUSO', 2, NULL, 0, NULL),
(0038, 'Doble Filo', 'Ataque arriesgado que también hiere seriamente al usuario.', 100, 15, 'ATAQUE', 'NORMAL', 120, NULL, 1, NULL, 0, NULL),
(0039, 'Látigo', 'Agita la cola para despistar al objetivo y reducir su Defensa.', 100, 30, 'ESTADO', 'NORMAL', 0, NULL, 1, 'DEFENSA-', 0, 1),
(0040, 'Picotazo Veneno', 'Lanza un aguijón tóxico que puede envenenar al objetivo.', 100, 35, 'ATAQUE', 'VENENO', 15, 'ENVENENADO', 1, NULL, 0, NULL),
(0041, 'Doble Ataque', 'Pincha dos veces con dos espinas. Puede envenenar.', 100, 20, 'ATAQUE', 'BICHO', 25, 'ENVENENADO', 1, NULL, 0, NULL),
(0042, 'Pin Misil', 'Lanza afiladas púas que hieren al objetivo de dos a cinco veces seguidas.', 95, 20, 'ATAQUE', 'BICHO', 25, NULL, 1, NULL, 0, NULL),
(0043, 'Malicioso', 'Intimida al objetivo con una mirada torva para reducir su Defensa.', 100, 30, 'ESTADO', 'NORMAL', 0, NULL, 1, 'DEFENSA-', 0, 1),
(0044, 'Mordisco', 'Un voraz bocado con dientes afilados que puede amedrentar al objetivo.', 100, 25, 'ATAQUE', 'NORMAL', 60, 'AMEDRENTADO', 1, NULL, 0, NULL),
(0045, 'Gruñido', 'Dulce gruñido que distrae al objetivo para que baje la guardia y reduce su Ataque.', 100, 40, 'ESTADO', 'NORMAL', 0, NULL, 1, 'ATAQUE-', 0, 1),
(0046, 'Rugido', 'Se lleva al objetivo, que es cambiado por otro Pokémon. Si es un Pokémon salvaje, acaba el combate.', 100, 20, 'ESTADO', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0047, 'Canto', 'Cantinela que hace dormir profundamente al objetivo.', 55, 15, 'ESTADO', 'NORMAL', 0, 'DORMIDO', 1, NULL, 0, NULL),
(0048, 'Supersónico', 'El cuerpo del usuario emite unas ondas sónicas raras que confunden al objetivo.', 55, 20, 'ESTADO', 'NORMAL', 0, 'CONFUSO', 1, NULL, 0, NULL),
(0049, 'Bomba Sónica', 'Lanza ondas de choque que restan 20 PS al objetivo.', 90, 20, 'ATAQUE', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0050, 'Anulación', 'Anula el último movimiento usado por el objetivo durante cuatro turnos.', 100, 20, 'ESTADO', 'NORMAL', 0, NULL, 4, NULL, 0, NULL),
(0051, 'Ácido', 'Rocía al objetivo con un ácido corrosivo. Puede reducir la Defensa Especial.', 100, 30, 'ATAQUE', 'VENENO', 40, NULL, 1, NULL, 0, NULL),
(0052, 'Ascuas', 'Ataca con llamas pequeñas que pueden causar quemaduras.', 100, 25, 'ATAQUE', 'FUEGO', 40, 'QUEMADO', 1, NULL, 0, NULL),
(0053, 'Lanzallamas', 'Ataca con una gran ráfaga de fuego que puede causar quemaduras.', 100, 15, 'ATAQUE', 'FUEGO', 90, 'QUEMADO', 1, NULL, 0, NULL),
(0054, 'Neblina', 'Rodea de una niebla blanquecina al bando del usuario e impide que el rival reduzca sus características durante cinco turnos.', 100, 30, 'ESTADO', 'HIELO', 0, NULL, 5, NULL, 0, NULL),
(0055, 'Pistola Agua', 'Ataca disparando agua con gran potencia.', 100, 25, 'ATAQUE', 'AGUA', 40, NULL, 1, NULL, 0, NULL),
(0056, 'Hidrobomba', 'Lanza una gran masa de agua a presión para atacar.', 80, 5, 'ATAQUE', 'AGUA', 110, NULL, 1, NULL, 0, NULL),
(0057, 'Surf', 'Inunda el terreno de combate con una ola gigante que golpea a los Pokémon adyacentes.', 100, 15, 'ATAQUE', 'AGUA', 90, NULL, 1, NULL, 0, NULL),
(0058, 'Rayo Hielo', 'Rayo de hielo que puede llegar a congelar.', 100, 10, 'ATAQUE', 'HIELO', 90, 'CONGELADO', 1, NULL, 0, NULL),
(0059, 'Ventisca', 'Tormenta de hielo que puede llegar a congelar.', 70, 5, 'ATAQUE', 'HIELO', 110, 'CONGELADO', 1, NULL, 0, NULL),
(0060, 'Psicorrayo', 'Extraño rayo que puede causar confusión.', 100, 20, 'ATAQUE', 'PSIQUICO', 65, 'CONFUSO', 1, NULL, 0, NULL),
(0061, 'Rayo Burbuja', 'Ráfaga de burbujas que puede reducir la Velocidad.', 100, 20, 'ATAQUE', 'AGUA', 65, NULL, 1, NULL, 0, NULL),
(0062, 'Rayo Aurora', 'Rayo multicolor que puede reducir el Ataque.', 100, 20, 'ATAQUE', 'HIELO', 65, NULL, 1, NULL, 0, NULL),
(0063, 'Hiperrayo', 'El usuario ataca al objetivo con un potente haz de luz, pero deberá descansar en el siguiente turno.', 90, 5, 'ATAQUE', 'NORMAL', 150, NULL, 2, NULL, 0, NULL),
(0064, 'Picotazo', 'Ensarta al objetivo con un cuerno o pico punzante.', 100, 35, 'ATAQUE', 'VOLADOR', 35, NULL, 1, NULL, 0, NULL),
(0065, 'Pico Taladro', 'Picotazo giratorio y perforador muy potente.', 100, 20, 'ATAQUE', 'VOLADOR', 80, NULL, 1, NULL, 0, NULL),
(0066, 'Sumisión', 'El usuario se lanza al suelo con el oponente en brazos y también se hace un poco de daño.', 80, 20, 'ATAQUE', 'LUCHA', 80, NULL, 1, NULL, 0, NULL),
(0067, 'Patada Baja', 'Patada baja que derriba al objetivo.', 100, 20, 'ATAQUE', 'LUCHA', 0, NULL, 1, NULL, 0, NULL),
(0068, 'Contraataque', 'Con más peso este, más daño le causa.', 100, 20, 'ATAQUE', 'LUCHA', 0, NULL, 1, NULL, 0, NULL),
(0069, 'Sísmico', 'Aprovecha la gravedad para derribar al objetivo. Le resta tantos PS como nivel tenga el usuario.', 100, 20, 'ATAQUE', 'LUCHA', 0, NULL, 1, NULL, 0, NULL),
(0070, 'Fuerza', 'Ataca al objetivo golpeándolo con todas sus fuerzas.', 100, 15, 'ATAQUE', 'NORMAL', 80, NULL, 1, NULL, 0, NULL),
(0071, 'Absorber', 'Un ataque que absorbe nutrientes. El usuario recupera la mitad de los PS del daño que produce.', 100, 25, 'ATAQUE', 'PLANTA', 20, NULL, 1, NULL, 0, NULL),
(0072, 'Megaagotar', 'Un ataque que absorbe nutrientes. El usuario recupera la mitad de los PS del daño que produce.', 100, 15, 'ATAQUE', 'PLANTA', 40, NULL, 1, NULL, 0, NULL),
(0073, 'Drenadoras', 'Planta semillas que absorben PS del objetivo en cada turno y que le sirven para recuperarse.', 90, 10, 'ESTADO', 'PLANTA', 0, 'DRENADORAS', 5, NULL, 0, NULL),
(0074, 'Desarrollo', 'Hace que su cuerpo crezca a marchas forzadas, con lo que aumenta su Ataque y su Ataque Especial.', 0, 20, 'MEJORA', 'NORMAL', 0, NULL, 1, 'ATAQUE+', 0, 1),
(0075, 'Hoja Afilada', 'Corta con hojas afiladas. Suele asestar un golpe crítico.', 95, 25, 'ATAQUE', 'PLANTA', 55, NULL, 1, NULL, 0, NULL),
(0076, 'Rayo Solar', 'El usuario absorbe luz en el primer turno y, en el segundo, lanza un potente rayo de energía.', 100, 10, 'ATAQUE', 'PLANTA', 120, NULL, 2, NULL, 0, NULL),
(0077, 'Polvo Veneno', 'Esparce polvo tóxico que envenena al objetivo.', 75, 35, 'ESTADO', 'VENENO', 0, 'ENVENENADO', 1, NULL, 0, NULL),
(0078, 'Paralizador', 'Esparce polvo que paraliza al objetivo.', 75, 30, 'ESTADO', 'PLANTA', 0, 'PARALIZADO', 1, NULL, 0, NULL),
(0079, 'Somnífero', 'Esparce polvo que duerme al objetivo.', 75, 15, 'ESTADO', 'PLANTA', 0, 'DORMIDO', 1, NULL, 0, NULL),
(0080, 'Danza Pétalo', 'Ataca al objetivo lanzando pétalos de dos a tres turnos y, al finalizar, el usuario se queda confuso.', 100, 10, 'ATAQUE', 'PLANTA', 120, 'CONFUSO', 2, NULL, 0, NULL),
(0081, 'Disparo Demora', 'Lanza seda por la boca al objetivo y reduce mucho su Velocidad.', 95, 40, 'ESTADO', 'BICHO', 0, NULL, 1, 'VELOCIDAD-', 0, 1),
(0082, 'Furia Dragón', 'Ráfaga de furiosas ondas de choque que quitan 40 PS.', 100, 10, 'ATAQUE', 'DRAGON', 0, NULL, 1, NULL, 0, NULL),
(0083, 'Giro Fuego', 'Un anillo de fuego que atrapa y daña al objetivo de cuatro a cinco turnos.', 85, 15, 'ATAQUE', 'FUEGO', 35, 'ATRAPADO', 4, NULL, 0, NULL),
(0084, 'Impactrueno', 'Ataque eléctrico que puede paralizar al objetivo.', 100, 30, 'ATAQUE', 'ELECTRICO', 40, 'PARALIZADO', 1, NULL, 0, NULL),
(0085, 'Rayo', 'Potente ataque eléctrico que puede paralizar al objetivo.', 100, 15, 'ATAQUE', 'ELECTRICO', 90, 'PARALIZADO', 1, NULL, 0, NULL),
(0086, 'Onda Trueno', 'Una ligera descarga que paraliza al objetivo.', 90, 20, 'ESTADO', 'ELECTRICO', 0, 'PARALIZADO', 1, NULL, 0, NULL),
(0087, 'Trueno', 'Un poderoso rayo que daña al objetivo y puede paralizarlo.', 70, 10, 'ATAQUE', 'ELECTRICO', 110, 'PARALIZADO', 1, NULL, 0, NULL),
(0088, 'Lanzarrocas', 'Tira una pequeña roca al objetivo.', 90, 15, 'ATAQUE', 'ROCA', 50, NULL, 1, NULL, 0, NULL),
(0089, 'Terremoto', 'Un terremoto que afecta a los Pokémon adyacentes.', 100, 10, 'ATAQUE', 'TIERRA', 100, NULL, 1, NULL, 0, NULL),
(0090, 'Fisura', 'Abre una grieta en el suelo y mete al objetivo en ella. Fulmina al objetivo de un solo golpe si acierta.', 30, 5, 'ATAQUE', 'TIERRA', 0, NULL, 1, NULL, 0, NULL),
(0091, 'Excavar', 'El usuario cava durante el primer turno y ataca en el segundo.', 100, 10, 'ATAQUE', 'TIERRA', 80, NULL, 2, NULL, 0, NULL),
(0092, 'Tóxico', 'Envenena gravemente al objetivo y causa un daño mayor en cada turno.', 90, 10, 'ESTADO', 'VENENO', 0, 'GRAVEMENTE ENVENENADO', 1, NULL, 0, NULL),
(0093, 'Confusión', 'Débil ataque telequinético que puede causar confusión.', 100, 25, 'ATAQUE', 'PSIQUICO', 50, 'CONFUSO', 1, NULL, 0, NULL),
(0094, 'Psíquico', 'Fuerte ataque telequinético que puede reducir la Defensa Especial del objetivo.', 100, 10, 'ATAQUE', 'PSIQUICO', 90, NULL, 1, NULL, 0, NULL),
(0095, 'Hipnosis', 'Ataque hipnótico que hace dormir profundamente al objetivo.', 60, 20, 'ESTADO', 'PSIQUICO', 0, 'DORMIDO', 1, NULL, 0, NULL),
(0096, 'Meditación', 'El usuario reposa y medita para potenciar el Ataque.', 100, 40, 'MEJORA', 'PSIQUICO', 0, NULL, 1, 'ATAQUE+', 0, 1),
(0097, 'Agilidad', 'Relaja y aligera el cuerpo para aumentar mucho la Velocidad.', 100, 30, 'MEJORA', 'PSIQUICO', 0, NULL, 1, 'VELOCIDAD+', 0, 2),
(0098, 'Ataque Rápido', 'Ataca al objetivo a tal velocidad que es casi imperceptible. Este movimiento tiene prioridad alta.', 100, 30, 'ATAQUE', 'NORMAL', 40, NULL, 1, NULL, 0, NULL),
(0099, 'Furia', 'Al usarse, aumenta el Ataque del usuario cada vez que es golpeado.', 100, 20, 'ATAQUE', 'NORMAL', 20, NULL, 1, NULL, 0, NULL),
(0100, 'Teletransporte', 'Permite al usuario cambiarse por otro Pokémon del equipo, si lo hay. Si un Pokémon salvaje usa este movimiento, huye del combate.', 100, 20, 'ESTADO', 'PSIQUICO', 0, NULL, 1, NULL, 0, NULL),
(0101, 'Tinieblas', 'Produce un espejismo ante el objetivo, que pierde tantos PS como nivel tenga el usuario.', 100, 15, 'ATAQUE', 'FANTASMA', 0, NULL, 1, NULL, 0, NULL),
(0102, 'Mimético', 'Copia el último movimiento usado por el objetivo, y puede utilizarlo mientras esté en el combate.', 100, 10, 'ESTADO', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0103, 'Chirrido', 'Chillido agudo que reduce mucho la Defensa del objetivo.', 85, 40, 'ESTADO', 'NORMAL', 0, NULL, 1, 'DEFENSA-', 0, 2),
(0104, 'Doble Equipo', 'El usuario se mueve a velocidad vertiginosa y crea copias ilusorias de sí mismo, con lo que aumenta su Evasión al desconcentrar al rival.', 100, 15, 'MEJORA', 'NORMAL', 0, NULL, 1, 'EVASION+', 0, 1),
(0105, 'Recuperación', 'El usuario regenera sus células y recupera una cantidad de PS equivalente a la mitad de sus PS máximos.', 100, 5, 'ESTADO', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0106, 'Fortaleza', 'El usuario tensa su musculatura para aumentar la Defensa.', 100, 30, 'MEJORA', 'NORMAL', 0, NULL, 1, 'DEFENSA+', 0, 1),
(0107, 'Reducción', 'El usuario mengua para aumentar mucho la Evasión.', 100, 10, 'MEJORA', 'NORMAL', 0, NULL, 1, 'EVASION+', 0, 2),
(0108, 'Pantalla de Humo', 'Reduce la Precisión del objetivo con una nube de humo o tinta.', 100, 20, 'ESTADO', 'NORMAL', 0, NULL, 1, 'PRECISION-', 0, 1),
(0109, 'Rayo Confuso', 'Rayo siniestro que confunde al objetivo.', 100, 10, 'ESTADO', 'FANTASMA', 0, 'CONFUSO', 1, NULL, 0, NULL),
(0110, 'Refugio', 'El usuario se resguarda en su coraza, por lo que le aumenta la Defensa.', 100, 40, 'MEJORA', 'NORMAL', 0, NULL, 1, 'DEFENSA+', 0, 1),
(0111, 'Rizo Defensa', 'Se enrosca para ocultar sus puntos débiles y aumenta la Defensa.', 100, 40, 'MEJORA', 'NORMAL', 0, NULL, 1, 'DEFENSA+', 0, 1),
(0112, 'Barrera', 'Crea una barrera que aumenta mucho la Defensa.', 100, 20, 'MEJORA', 'PSIQUICO', 0, NULL, 1, 'DEFENSA+', 0, 2),
(0113, 'Pantalla de Luz', 'Barrera misteriosa que reduce durante cinco turnos el daño producido por los ataques especiales del rival.', 100, 30, 'MEJORA', 'PSIQUICO', 0, NULL, 5, NULL, 0, NULL),
(0114, 'Niebla', 'Neblina oscura que elimina los cambios en las características de todos los Pokémon en combate.', 100, 30, 'ESTADO', 'HIELO', 0, NULL, 5, NULL, 0, NULL),
(0115, 'Reflejo', 'Barrera misteriosa que reduce durante cinco turnos el daño producido por los ataques físicos del rival.', 100, 20, 'MEJORA', 'PSIQUICO', 0, NULL, 5, NULL, 0, NULL),
(0116, 'Foco Energía', 'Concentra energía para aumentar las posibilidades de asestar un golpe crítico.', 100, 30, 'MEJORA', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0117, 'Venganza', 'Espera dos turnos para atacar con el doble de potencia del daño recibido.', 100, 10, 'ATAQUE', 'NORMAL', 0, NULL, 2, NULL, 0, NULL),
(0118, 'Metrónomo', 'Mueve un dedo y estimula su cerebro para usar al azar casi cualquier movimiento.', 100, 10, 'ESTADO', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0119, 'Espejo', 'Ataca al objetivo con el último movimiento que este haya usado.', 0, 20, 'ATAQUE', 'VOLADOR', 0, NULL, 1, NULL, 0, NULL),
(0120, 'Autodestrucción', 'El atacante explota y hiere a los Pokémon adyacentes. El usuario se debilita de inmediato.', 100, 5, 'ATAQUE', 'NORMAL', 200, NULL, 1, NULL, 0, NULL),
(0121, 'Bomba Huevo', 'Arroja un huevo enorme al objetivo con gran fuerza.', 75, 10, 'ATAQUE', 'NORMAL', 100, NULL, 1, NULL, 0, NULL),
(0122, 'Lengüetazo', 'El usuario ataca al objetivo lamiéndolo con su larga lengua. Puede causar parálisis.', 100, 30, 'ATAQUE', 'FANTASMA', 30, 'PARALIZADO', 1, NULL, 0, NULL),
(0123, 'Polución', 'Lanza un ataque con gases tóxicos que pueden llegar a envenenar.', 70, 20, 'ATAQUE', 'VENENO', 30, 'ENVENENADO', 1, NULL, 0, NULL),
(0124, 'Residuos', 'Arroja residuos al objetivo. Puede llegar a envenenar.', 100, 20, 'ATAQUE', 'VENENO', 65, 'ENVENENADO', 1, NULL, 0, NULL),
(0125, 'Hueso Palo', 'Aporrea con un hueso. Puede hacer retroceder al objetivo.', 85, 20, 'ATAQUE', 'TIERRA', 65, NULL, 1, NULL, 0, NULL),
(0126, 'Llamarada', 'Llama intensa que chamusca y puede causar quemaduras.', 85, 5, 'ATAQUE', 'FUEGO', 110, 'QUEMADO', 1, NULL, 0, NULL),
(0127, 'Cascada', 'Embiste con un gran impulso y puede llegar a amedrentar al objetivo.', 100, 15, 'ATAQUE', 'AGUA', 80, 'AMEDRENTADO', 1, NULL, 0, NULL),
(0128, 'Clamp', 'Atrapa y atenaza con fuerza durante cuatro o cinco turnos.', 85, 15, 'ATAQUE', 'AGUA', 35, 'ATRAPADO', 4, NULL, 0, NULL),
(0129, 'Rayo Estrella', 'Lanza rayos en forma de estrella que no fallan nunca.', 100, 20, 'ATAQUE', 'NORMAL', 60, NULL, 1, NULL, 0, NULL),
(0130, 'Cabezazo', 'El usuario se prepara y sube su Defensa en el primer turno y en el segundo arremete con un cabezazo.', 100, 10, 'ATAQUE', 'NORMAL', 130, NULL, 2, NULL, 0, NULL),
(0131, 'Clavo Cañón', 'Enquista los sueños de un objetivo dormido. El usuario recupera la mitad de los PS del daño que produce.', 100, 15, 'ATAQUE', 'PSIQUICO', 0, NULL, 1, NULL, 0, NULL),
(0132, 'Restricción', 'Ataca con largos tentáculos o zarcillos que pueden bajar la Velocidad.', 100, 35, 'ATAQUE', 'NORMAL', 10, NULL, 1, NULL, 0, NULL),
(0133, 'Amnesia', 'El usuario olvida sus preocupaciones y aumenta mucho la Defensa Especial.', 100, 20, 'MEJORA', 'PSIQUICO', 0, NULL, 1, 'DEFENSA ESPECIAL+', 0, 2),
(0134, 'Kinético', 'Debilita una cuchara para distraer al objetivo y reducir su Precisión.', 80, 15, 'ESTADO', 'PSIQUICO', 0, NULL, 1, 'PRECISION-', 0, 1),
(0135, 'Ovocuración', 'Restaura la mitad de los PS máximos del usuario.', 100, 5, 'ESTADO', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0136, 'Patada Salto Alta', 'El usuario salta muy alto y propina un rodillazo al objetivo. Si falla, se hiere a sí mismo.', 90, 10, 'ATAQUE', 'LUCHA', 130, NULL, 1, NULL, 0, NULL),
(0137, 'Deslumbrar', 'Intimida y asusta al objetivo con la mirada para dejarlo paralizado.', 75, 30, 'ESTADO', 'NORMAL', 0, 'PARALIZADO', 1, NULL, 0, NULL),
(0138, 'Comesueños', 'Enquile los sueños de un objetivo dormido. El usuario recupera la mitad de los PS del daño que produce.', 100, 15, 'ATAQUE', 'PSIQUICO', 100, NULL, 1, NULL, 0, NULL),
(0139, 'Gas Venenoso', 'Lanza una nube de gas tóxico al rostro del objetivo. Produce envenenamiento.', 90, 40, 'ESTADO', 'VENENO', 0, 'ENVENENADO', 1, NULL, 0, NULL),
(0140, 'Bombardeo', 'Arroja esferas al objetivo entre dos y cinco veces seguidas.', 85, 20, 'ATAQUE', 'NORMAL', 15, NULL, 1, NULL, 0, NULL),
(0141, 'Chupavidas', 'Chupa sangre al objetivo. El usuario recupera la mitad de los PS del daño que produce.', 100, 10, 'ATAQUE', 'BICHO', 80, NULL, 1, NULL, 0, NULL),
(0142, 'Beso Amoroso', 'Intimida al objetivo con una cara que asusta y le da un beso que lo deja dormido.', 75, 10, 'ESTADO', 'NORMAL', 0, 'DORMIDO', 1, NULL, 0, NULL),
(0143, 'Ataque Aéreo', 'Ataca en el segundo turno y suele asestar un golpe crítico. También puede amedrentar al objetivo.', 90, 5, 'ATAQUE', 'VOLADOR', 140, 'AMEDRENTADO', 2, NULL, 0, NULL),
(0144, 'Transformación', 'El usuario se transforma en una copia del objetivo, con los mismos movimientos.', 100, 10, 'ESTADO', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0145, 'Burbuja', 'Lanza burbujas a los contrincantes y puede reducir su Velocidad.', 100, 30, 'ATAQUE', 'AGUA', 40, NULL, 1, NULL, 0, NULL),
(0146, 'Puño Mareo', 'Rítmicos puñetazos que pueden causar confusión.', 100, 10, 'ATAQUE', 'NORMAL', 70, 'CONFUSO', 1, NULL, 0, NULL),
(0147, 'Espora', 'Esparce esporas que inducen el sueño.', 100, 15, 'ESTADO', 'PLANTA', 0, 'DORMIDO', 1, NULL, 0, NULL),
(0148, 'Destello', 'Luz cegadora que baja la Precisión del objetivo.', 100, 20, 'ESTADO', 'NORMAL', 0, NULL, 1, 'PRECISION-', 0, 1),
(0149, 'Psicoonda', 'Ataca con una onda de energía de intensidad variable.', 100, 15, 'ATAQUE', 'PSIQUICO', 0, NULL, 1, NULL, 0, NULL),
(0150, 'Salpicadura', 'No tiene ningún efecto. Solo salpica.', 100, 40, 'ESTADO', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0151, 'Armadura Ácida', 'Transforma su estructura celular para hacerse líquido y aumentar mucho la Defensa.', 100, 20, 'MEJORA', 'VENENO', 0, NULL, 1, 'DEFENSA+', 0, 2),
(0152, 'Martillazo', 'Golpea con fuerza con una pinza enorme. Suele asestar un golpe crítico.', 90, 10, 'ATAQUE', 'AGUA', 100, NULL, 1, NULL, 0, NULL),
(0153, 'Explosión', 'El atacante causa una grandísima explosión y hiere a los Pokémon adyacentes. El usuario se debilita de inmediato.', 100, 5, 'ATAQUE', 'NORMAL', 250, NULL, 1, NULL, 0, NULL),
(0154, 'Golpes Furia', 'Araña al objetivo con uñas, cuchillas o similares de dos a cinco veces seguidas.', 80, 15, 'ATAQUE', 'NORMAL', 18, NULL, 1, NULL, 0, NULL),
(0155, 'Huesomerang', 'Lanza el hueso que lleva a modo de bumerán contra el objetivo y le inflige daño dos veces seguidas.', 90, 10, 'ATAQUE', 'TIERRA', 50, NULL, 1, NULL, 0, NULL),
(0156, 'Descanso', 'Restaura todos los PS y cura todos los problemas de estado del usuario, que se duerme los dos turnos siguientes.', 100, 10, 'ESTADO', 'PSIQUICO', 0, NULL, 2, NULL, 0, NULL),
(0157, 'Avalancha', 'Lanza grandes pedruscos. Puede amedrentar al objetivo.', 90, 10, 'ATAQUE', 'ROCA', 75, 'AMEDRENTADO', 1, NULL, 0, NULL),
(0158, 'Hipercolmillo', 'Ataca con agudos colmillos. Puede amedrentar al objetivo.', 90, 15, 'ATAQUE', 'NORMAL', 80, 'AMEDRENTADO', 1, NULL, 0, NULL),
(0159, 'Afilar', 'El perfil del usuario se hace más afilado y su Ataque mejora.', 100, 30, 'MEJORA', 'NORMAL', 0, NULL, 1, 'ATAQUE+', 0, 1),
(0160, 'Conversión', 'Cambia el tipo del usuario por el del primer movimiento en su lista.', 100, 30, 'MEJORA', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0161, 'Triataque', 'Ataca con tres rayos de luz que puede paralizar, quemar o congelar al objetivo.', 100, 10, 'ATAQUE', 'NORMAL', 80, NULL, 1, NULL, 0, NULL),
(0162, 'Superdiente', 'Asesta una dentellada con sus afilados incisivos que reduce a la mitad los PS del objetivo.', 90, 10, 'ATAQUE', 'NORMAL', 50, NULL, 1, NULL, 0, NULL),
(0163, 'Cuchillada', 'Ataca con cuchillas o con pinzas. Suele asestar un golpe crítico.', 100, 20, 'ATAQUE', 'NORMAL', 70, NULL, 1, NULL, 0, NULL),
(0164, 'Sustituto', 'Utiliza parte de los PS propios para crear un sustituto que actúa como señuelo.', 0, 10, 'ESTADO', 'NORMAL', 0, NULL, 1, NULL, 0, NULL),
(0165, 'Forcejeo', 'Solo se usa como último recurso al acabarse los PP. El usuario se hiere ligeramente a sí mismo.', 100, 1, 'ATAQUE', 'NORMAL', 50, NULL, 1, NULL, 0, NULL);


-- Método INSERT con todas las rutas de imágenes, sprites y sonidos
INSERT INTO POKEDEX (NUM_POKEDEX, NOM_POKEMON, IMG_FRONTAL, IMG_TRASERA, SPRITES_FRONTAL, SPRITES_TRASEROS, SONIDO, NIVEL_EVOLUCION, TIPO1, TIPO2) VALUES
(1, 'BULBASAUR', 'multimedia/imagenes/delanteras/1.png', 'multimedia/imagenes/traseras/1.png', 'multimedia/sprites/delanteras/1.gif', 'multimedia/sprites/traseras/1.gif', 'multimedia/sonidos/cries_pokemon_legacy_1.ogg', 1, 'PLANTA', 'VENENO'),
(2, 'IVYSAUR', 'multimedia/imagenes/delanteras/2.png', 'multimedia/imagenes/traseras/2.png', 'multimedia/sprites/delanteras/2.gif', 'multimedia/sprites/traseras/2.gif', 'multimedia/sonidos/cries_pokemon_legacy_2.ogg', 2, 'PLANTA', 'VENENO'),
(3, 'VENUSAUR', 'multimedia/imagenes/delanteras/3.png', 'multimedia/imagenes/traseras/3.png', 'multimedia/sprites/delanteras/3.gif', 'multimedia/sprites/traseras/3.gif', 'multimedia/sonidos/cries_pokemon_legacy_3.ogg', 3, 'PLANTA', 'VENENO'),
(4, 'CHARMANDER', 'multimedia/imagenes/delanteras/4.png', 'multimedia/imagenes/traseras/4.png', 'multimedia/sprites/delanteras/4.gif', 'multimedia/sprites/traseras/4.gif', 'multimedia/sonidos/cries_pokemon_legacy_4.ogg', 1, 'FUEGO', NULL),
(5, 'CHARMELEON', 'multimedia/imagenes/delanteras/5.png', 'multimedia/imagenes/traseras/5.png', 'multimedia/sprites/delanteras/5.gif', 'multimedia/sprites/traseras/5.gif', 'multimedia/sonidos/cries_pokemon_legacy_5.ogg', 2, 'FUEGO', NULL),
(6, 'CHARIZARD', 'multimedia/imagenes/delanteras/6.png', 'multimedia/imagenes/traseras/6.png', 'multimedia/sprites/delanteras/6.gif', 'multimedia/sprites/traseras/6.gif', 'multimedia/sonidos/cries_pokemon_legacy_6.ogg', 3, 'FUEGO', 'VOLADOR'),
(7, 'SQUIRTLE', 'multimedia/imagenes/delanteras/7.png', 'multimedia/imagenes/traseras/7.png', 'multimedia/sprites/delanteras/7.gif', 'multimedia/sprites/traseras/7.gif', 'multimedia/sonidos/cries_pokemon_legacy_7.ogg', 1, 'AGUA', NULL),
(8, 'WARTORTLE', 'multimedia/imagenes/delanteras/8.png', 'multimedia/imagenes/traseras/8.png', 'multimedia/sprites/delanteras/8.gif', 'multimedia/sprites/traseras/8.gif', 'multimedia/sonidos/cries_pokemon_legacy_8.ogg', 2, 'AGUA', NULL),
(9, 'BLASTOISE', 'multimedia/imagenes/delanteras/9.png', 'multimedia/imagenes/traseras/9.png', 'multimedia/sprites/delanteras/9.gif', 'multimedia/sprites/traseras/9.gif', 'multimedia/sonidos/cries_pokemon_legacy_9.ogg', 3, 'AGUA', NULL),
(10, 'CATERPIE', 'multimedia/imagenes/delanteras/10.png', 'multimedia/imagenes/traseras/10.png', 'multimedia/sprites/delanteras/10.gif', 'multimedia/sprites/traseras/10.gif', 'multimedia/sonidos/cries_pokemon_legacy_10.ogg', 1, 'BICHO', NULL),
(11, 'METAPOD', 'multimedia/imagenes/delanteras/11.png', 'multimedia/imagenes/traseras/11.png', 'multimedia/sprites/delanteras/11.gif', 'multimedia/sprites/traseras/11.gif', 'multimedia/sonidos/cries_pokemon_legacy_11.ogg', 2, 'BICHO', NULL),
(12, 'BUTTERFREE', 'multimedia/imagenes/delanteras/12.png', 'multimedia/imagenes/traseras/12.png', 'multimedia/sprites/delanteras/12.gif', 'multimedia/sprites/traseras/12.gif', 'multimedia/sonidos/cries_pokemon_legacy_12.ogg', 3, 'BICHO', 'VOLADOR'),
(13, 'WEEDLE', 'multimedia/imagenes/delanteras/13.png', 'multimedia/imagenes/traseras/13.png', 'multimedia/sprites/delanteras/13.gif', 'multimedia/sprites/traseras/13.gif', 'multimedia/sonidos/cries_pokemon_legacy_13.ogg', 1, 'BICHO', 'VENENO'),
(14, 'KAKUNA', 'multimedia/imagenes/delanteras/14.png', 'multimedia/imagenes/traseras/14.png', 'multimedia/sprites/delanteras/14.gif', 'multimedia/sprites/traseras/14.gif', 'multimedia/sonidos/cries_pokemon_legacy_14.ogg', 2, 'BICHO', 'VENENO'),
(15, 'BEEDRILL', 'multimedia/imagenes/delanteras/15.png', 'multimedia/imagenes/traseras/15.png', 'multimedia/sprites/delanteras/15.gif', 'multimedia/sprites/traseras/15.gif', 'multimedia/sonidos/cries_pokemon_legacy_15.ogg', 3, 'BICHO', 'VENENO'),
(16, 'PIDGEY', 'multimedia/imagenes/delanteras/16.png', 'multimedia/imagenes/traseras/16.png', 'multimedia/sprites/delanteras/16.gif', 'multimedia/sprites/traseras/16.gif', 'multimedia/sonidos/cries_pokemon_legacy_16.ogg', 1, 'NORMAL', 'VOLADOR'),
(17, 'PIDGEOTTO', 'multimedia/imagenes/delanteras/17.png', 'multimedia/imagenes/traseras/17.png', 'multimedia/sprites/delanteras/17.gif', 'multimedia/sprites/traseras/17.gif', 'multimedia/sonidos/cries_pokemon_legacy_17.ogg', 2, 'NORMAL', 'VOLADOR'),
(18, 'PIDGEOT', 'multimedia/imagenes/delanteras/18.png', 'multimedia/imagenes/traseras/18.png', 'multimedia/sprites/delanteras/18.gif', 'multimedia/sprites/traseras/18.gif', 'multimedia/sonidos/cries_pokemon_legacy_18.ogg', 3, 'NORMAL', 'VOLADOR'),
(19, 'RATTATA', 'multimedia/imagenes/delanteras/19.png', 'multimedia/imagenes/traseras/19.png', 'multimedia/sprites/delanteras/19.gif', 'multimedia/sprites/traseras/19.gif', 'multimedia/sonidos/cries_pokemon_legacy_19.ogg', 1, 'NORMAL', NULL),
(20, 'RATICATE', 'multimedia/imagenes/delanteras/20.png', 'multimedia/imagenes/traseras/20.png', 'multimedia/sprites/delanteras/20.gif', 'multimedia/sprites/traseras/20.gif', 'multimedia/sonidos/cries_pokemon_legacy_20.ogg', 2, 'NORMAL', NULL),
(21, 'SPEAROW', 'multimedia/imagenes/delanteras/21.png', 'multimedia/imagenes/traseras/21.png', 'multimedia/sprites/delanteras/21.gif', 'multimedia/sprites/traseras/21.gif', 'multimedia/sonidos/cries_pokemon_legacy_21.ogg', 1, 'NORMAL', 'VOLADOR'),
(22, 'FEAROW', 'multimedia/imagenes/delanteras/22.png', 'multimedia/imagenes/traseras/22.png', 'multimedia/sprites/delanteras/22.gif', 'multimedia/sprites/traseras/22.gif', 'multimedia/sonidos/cries_pokemon_legacy_22.ogg', 2, 'NORMAL', 'VOLADOR'),
(23, 'EKANS', 'multimedia/imagenes/delanteras/23.png', 'multimedia/imagenes/traseras/23.png', 'multimedia/sprites/delanteras/23.gif', 'multimedia/sprites/traseras/23.gif', 'multimedia/sonidos/cries_pokemon_legacy_23.ogg', 1, 'VENENO', NULL),
(24, 'ARBOK', 'multimedia/imagenes/delanteras/24.png', 'multimedia/imagenes/traseras/24.png', 'multimedia/sprites/delanteras/24.gif', 'multimedia/sprites/traseras/24.gif', 'multimedia/sonidos/cries_pokemon_legacy_24.ogg', 2, 'VENENO', NULL),
(25, 'PIKACHU', 'multimedia/imagenes/delanteras/25.png', 'multimedia/imagenes/traseras/25.png', 'multimedia/sprites/delanteras/25.gif', 'multimedia/sprites/traseras/25.gif', 'multimedia/sonidos/cries_pokemon_legacy_25.ogg', 1, 'ELÉCTRICO', NULL),
(26, 'RAICHU', 'multimedia/imagenes/delanteras/26.png', 'multimedia/imagenes/traseras/26.png', 'multimedia/sprites/delanteras/26.gif', 'multimedia/sprites/traseras/26.gif', 'multimedia/sonidos/cries_pokemon_legacy_26.ogg', 2, 'ELÉCTRICO', NULL),
(27, 'SANDSHREW', 'multimedia/imagenes/delanteras/27.png', 'multimedia/imagenes/traseras/27.png', 'multimedia/sprites/delanteras/27.gif', 'multimedia/sprites/traseras/27.gif', 'multimedia/sonidos/cries_pokemon_legacy_27.ogg', 1, 'TIERRA', NULL),
(28, 'SANDSLASH', 'multimedia/imagenes/delanteras/28.png', 'multimedia/imagenes/traseras/28.png', 'multimedia/sprites/delanteras/28.gif', 'multimedia/sprites/traseras/28.gif', 'multimedia/sonidos/cries_pokemon_legacy_28.ogg', 2, 'TIERRA', NULL),
(29, 'NIDORAN♀', 'multimedia/imagenes/delanteras/29.png', 'multimedia/imagenes/traseras/29.png', 'multimedia/sprites/delanteras/29.gif', 'multimedia/sprites/traseras/29.gif', 'multimedia/sonidos/cries_pokemon_legacy_29.ogg', 1, 'VENENO', NULL),
(30, 'NIDORINA', 'multimedia/imagenes/delanteras/30.png', 'multimedia/imagenes/traseras/30.png', 'multimedia/sprites/delanteras/30.gif', 'multimedia/sprites/traseras/30.gif', 'multimedia/sonidos/cries_pokemon_legacy_30.ogg', 2, 'VENENO', NULL),
(31, 'NIDOQUEEN', 'multimedia/imagenes/delanteras/31.png', 'multimedia/imagenes/traseras/31.png', 'multimedia/sprites/delanteras/31.gif', 'multimedia/sprites/traseras/31.gif', 'multimedia/sonidos/cries_pokemon_legacy_31.ogg', 3, 'VENENO', 'TIERRA'),
(32, 'NIDORAN♂', 'multimedia/imagenes/delanteras/32.png', 'multimedia/imagenes/traseras/32.png', 'multimedia/sprites/delanteras/32.gif', 'multimedia/sprites/traseras/32.gif', 'multimedia/sonidos/cries_pokemon_legacy_32.ogg', 1, 'VENENO', NULL),
(33, 'NIDORINO', 'multimedia/imagenes/delanteras/33.png', 'multimedia/imagenes/traseras/33.png', 'multimedia/sprites/delanteras/33.gif', 'multimedia/sprites/traseras/33.gif', 'multimedia/sonidos/cries_pokemon_legacy_33.ogg', 2, 'VENENO', NULL),
(34, 'NIDOKING', 'multimedia/imagenes/delanteras/34.png', 'multimedia/imagenes/traseras/34.png', 'multimedia/sprites/delanteras/34.gif', 'multimedia/sprites/traseras/34.gif', 'multimedia/sonidos/cries_pokemon_legacy_34.ogg', 3, 'VENENO', 'TIERRA'),
(35, 'CLEFAIRY', 'multimedia/imagenes/delanteras/35.png', 'multimedia/imagenes/traseras/35.png', 'multimedia/sprites/delanteras/35.gif', 'multimedia/sprites/traseras/35.gif', 'multimedia/sonidos/cries_pokemon_legacy_35.ogg', 1, 'NORMAL', NULL),
(36, 'CLEFABLE', 'multimedia/imagenes/delanteras/36.png', 'multimedia/imagenes/traseras/36.png', 'multimedia/sprites/delanteras/36.gif', 'multimedia/sprites/traseras/36.gif', 'multimedia/sonidos/cries_pokemon_legacy_36.ogg', 2, 'NORMAL', NULL),
(37, 'VULPIX', 'multimedia/imagenes/delanteras/37.png', 'multimedia/imagenes/traseras/37.png', 'multimedia/sprites/delanteras/37.gif', 'multimedia/sprites/traseras/37.gif', 'multimedia/sonidos/cries_pokemon_legacy_37.ogg', 1, 'FUEGO', NULL),
(38, 'NINETALES', 'multimedia/imagenes/delanteras/38.png', 'multimedia/imagenes/traseras/38.png', 'multimedia/sprites/delanteras/38.gif', 'multimedia/sprites/traseras/38.gif', 'multimedia/sonidos/cries_pokemon_legacy_38.ogg', 2, 'FUEGO', NULL),
(39, 'JIGGLYPUFF', 'multimedia/imagenes/delanteras/39.png', 'multimedia/imagenes/traseras/39.png', 'multimedia/sprites/delanteras/39.gif', 'multimedia/sprites/traseras/39.gif', 'multimedia/sonidos/cries_pokemon_legacy_39.ogg', 1, 'NORMAL', NULL),
(40, 'WIGGLYTUFF', 'multimedia/imagenes/delanteras/40.png', 'multimedia/imagenes/traseras/40.png', 'multimedia/sprites/delanteras/40.gif', 'multimedia/sprites/traseras/40.gif', 'multimedia/sonidos/cries_pokemon_legacy_40.ogg', 2, 'NORMAL', NULL),
(41, 'ZUBAT', 'multimedia/imagenes/delanteras/41.png', 'multimedia/imagenes/traseras/41.png', 'multimedia/sprites/delanteras/41.gif', 'multimedia/sprites/traseras/41.gif', 'multimedia/sonidos/cries_pokemon_legacy_41.ogg', 1, 'VENENO', 'VOLADOR'),
(42, 'GOLBAT', 'multimedia/imagenes/delanteras/42.png', 'multimedia/imagenes/traseras/42.png', 'multimedia/sprites/delanteras/42.gif', 'multimedia/sprites/traseras/42.gif', 'multimedia/sonidos/cries_pokemon_legacy_42.ogg', 2, 'VENENO', 'VOLADOR'),
(43, 'ODDISH', 'multimedia/imagenes/delanteras/43.png', 'multimedia/imagenes/traseras/43.png', 'multimedia/sprites/delanteras/43.gif', 'multimedia/sprites/traseras/43.gif', 'multimedia/sonidos/cries_pokemon_legacy_43.ogg', 1, 'PLANTA', 'VENENO'),
(44, 'GLOOM', 'multimedia/imagenes/delanteras/44.png', 'multimedia/imagenes/traseras/44.png', 'multimedia/sprites/delanteras/44.gif', 'multimedia/sprites/traseras/44.gif', 'multimedia/sonidos/cries_pokemon_legacy_44.ogg', 2, 'PLANTA', 'VENENO'),
(45, 'VILEPLUME', 'multimedia/imagenes/delanteras/45.png', 'multimedia/imagenes/traseras/45.png', 'multimedia/sprites/delanteras/45.gif', 'multimedia/sprites/traseras/45.gif', 'multimedia/sonidos/cries_pokemon_legacy_45.ogg', 3, 'PLANTA', 'VENENO'),
(46, 'PARAS', 'multimedia/imagenes/delanteras/46.png', 'multimedia/imagenes/traseras/46.png', 'multimedia/sprites/delanteras/46.gif', 'multimedia/sprites/traseras/46.gif', 'multimedia/sonidos/cries_pokemon_legacy_46.ogg', 1, 'BICHO', 'PLANTA'),
(47, 'PARASECT', 'multimedia/imagenes/delanteras/47.png', 'multimedia/imagenes/traseras/47.png', 'multimedia/sprites/delanteras/47.gif', 'multimedia/sprites/traseras/47.gif', 'multimedia/sonidos/cries_pokemon_legacy_47.ogg', 2, 'BICHO', 'PLANTA'),
(48, 'VENONAT', 'multimedia/imagenes/delanteras/48.png', 'multimedia/imagenes/traseras/48.png', 'multimedia/sprites/delanteras/48.gif', 'multimedia/sprites/traseras/48.gif', 'multimedia/sonidos/cries_pokemon_legacy_48.ogg', 1, 'BICHO', 'VENENO'),
(49, 'VENOMOTH', 'multimedia/imagenes/delanteras/49.png', 'multimedia/imagenes/traseras/49.png', 'multimedia/sprites/delanteras/49.gif', 'multimedia/sprites/traseras/49.gif', 'multimedia/sonidos/cries_pokemon_legacy_49.ogg', 2, 'BICHO', 'VENENO'),
(50, 'DIGLETT', 'multimedia/imagenes/delanteras/50.png', 'multimedia/imagenes/traseras/50.png', 'multimedia/sprites/delanteras/50.gif', 'multimedia/sprites/traseras/50.gif', 'multimedia/sonidos/cries_pokemon_legacy_50.ogg', 1, 'TIERRA', NULL),
(51, 'DUGTRIO', 'multimedia/imagenes/delanteras/51.png', 'multimedia/imagenes/traseras/51.png', 'multimedia/sprites/delanteras/51.gif', 'multimedia/sprites/traseras/51.gif', 'multimedia/sonidos/cries_pokemon_legacy_51.ogg', 2, 'TIERRA', NULL),
(52, 'MEOWTH', 'multimedia/imagenes/delanteras/52.png', 'multimedia/imagenes/traseras/52.png', 'multimedia/sprites/delanteras/52.gif', 'multimedia/sprites/traseras/52.gif', 'multimedia/sonidos/cries_pokemon_legacy_52.ogg', 1, 'NORMAL', NULL),
(53, 'PERSIAN', 'multimedia/imagenes/delanteras/53.png', 'multimedia/imagenes/traseras/53.png', 'multimedia/sprites/delanteras/53.gif', 'multimedia/sprites/traseras/53.gif', 'multimedia/sonidos/cries_pokemon_legacy_53.ogg', 2, 'NORMAL', NULL),
(54, 'PSYDUCK', 'multimedia/imagenes/delanteras/54.png', 'multimedia/imagenes/traseras/54.png', 'multimedia/sprites/delanteras/54.gif', 'multimedia/sprites/traseras/54.gif', 'multimedia/sonidos/cries_pokemon_legacy_54.ogg', 1, 'AGUA', NULL),
(55, 'GOLDUCK', 'multimedia/imagenes/delanteras/55.png', 'multimedia/imagenes/traseras/55.png', 'multimedia/sprites/delanteras/55.gif', 'multimedia/sprites/traseras/55.gif', 'multimedia/sonidos/cries_pokemon_legacy_55.ogg', 2, 'AGUA', NULL),
(56, 'MANKEY', 'multimedia/imagenes/delanteras/56.png', 'multimedia/imagenes/traseras/56.png', 'multimedia/sprites/delanteras/56.gif', 'multimedia/sprites/traseras/56.gif', 'multimedia/sonidos/cries_pokemon_legacy_56.ogg', 1, 'LUCHA', NULL),
(57, 'PRIMEAPE', 'multimedia/imagenes/delanteras/57.png', 'multimedia/imagenes/traseras/57.png', 'multimedia/sprites/delanteras/57.gif', 'multimedia/sprites/traseras/57.gif', 'multimedia/sonidos/cries_pokemon_legacy_57.ogg', 2, 'LUCHA', NULL),
(58, 'GROWLITHE', 'multimedia/imagenes/delanteras/58.png', 'multimedia/imagenes/traseras/58.png', 'multimedia/sprites/delanteras/58.gif', 'multimedia/sprites/traseras/58.gif', 'multimedia/sonidos/cries_pokemon_legacy_58.ogg', 1, 'FUEGO', NULL),
(59, 'ARCANINE', 'multimedia/imagenes/delanteras/59.png', 'multimedia/imagenes/traseras/59.png', 'multimedia/sprites/delanteras/59.gif', 'multimedia/sprites/traseras/59.gif', 'multimedia/sonidos/cries_pokemon_legacy_59.ogg', 2, 'FUEGO', NULL),
(60, 'POLIWAG', 'multimedia/imagenes/delanteras/60.png', 'multimedia/imagenes/traseras/60.png', 'multimedia/sprites/delanteras/60.gif', 'multimedia/sprites/traseras/60.gif', 'multimedia/sonidos/cries_pokemon_legacy_60.ogg', 1, 'AGUA', NULL),
(61, 'POLIWHIRL', 'multimedia/imagenes/delanteras/61.png', 'multimedia/imagenes/traseras/61.png', 'multimedia/sprites/delanteras/61.gif', 'multimedia/sprites/traseras/61.gif', 'multimedia/sonidos/cries_pokemon_legacy_61.ogg', 2, 'AGUA', NULL),
(62, 'POLIWRATH', 'multimedia/imagenes/delanteras/62.png', 'multimedia/imagenes/traseras/62.png', 'multimedia/sprites/delanteras/62.gif', 'multimedia/sprites/traseras/62.gif', 'multimedia/sonidos/cries_pokemon_legacy_62.ogg', 3, 'AGUA', 'LUCHA'),
(63, 'ABRA', 'multimedia/imagenes/delanteras/63.png', 'multimedia/imagenes/traseras/63.png', 'multimedia/sprites/delanteras/63.gif', 'multimedia/sprites/traseras/63.gif', 'multimedia/sonidos/cries_pokemon_legacy_63.ogg', 1, 'PSÍQUICO', NULL),
(64, 'KADABRA', 'multimedia/imagenes/delanteras/64.png', 'multimedia/imagenes/traseras/64.png', 'multimedia/sprites/delanteras/64.gif', 'multimedia/sprites/traseras/64.gif', 'multimedia/sonidos/cries_pokemon_legacy_64.ogg', 2, 'PSÍQUICO', NULL),
(65, 'ALAKAZAM', 'multimedia/imagenes/delanteras/65.png', 'multimedia/imagenes/traseras/65.png', 'multimedia/sprites/delanteras/65.gif', 'multimedia/sprites/traseras/65.gif', 'multimedia/sonidos/cries_pokemon_legacy_65.ogg', 3, 'PSÍQUICO', NULL),
(66, 'MACHOP', 'multimedia/imagenes/delanteras/66.png', 'multimedia/imagenes/traseras/66.png', 'multimedia/sprites/delanteras/66.gif', 'multimedia/sprites/traseras/66.gif', 'multimedia/sonidos/cries_pokemon_legacy_66.ogg', 1, 'LUCHA', NULL),
(67, 'MACHOKE', 'multimedia/imagenes/delanteras/67.png', 'multimedia/imagenes/traseras/67.png', 'multimedia/sprites/delanteras/67.gif', 'multimedia/sprites/traseras/67.gif', 'multimedia/sonidos/cries_pokemon_legacy_67.ogg', 2, 'LUCHA', NULL),
(68, 'MACHAMP', 'multimedia/imagenes/delanteras/68.png', 'multimedia/imagenes/traseras/68.png', 'multimedia/sprites/delanteras/68.gif', 'multimedia/sprites/traseras/68.gif', 'multimedia/sonidos/cries_pokemon_legacy_68.ogg', 3, 'LUCHA', NULL),
(69, 'BELLSPROUT', 'multimedia/imagenes/delanteras/69.png', 'multimedia/imagenes/traseras/69.png', 'multimedia/sprites/delanteras/69.gif', 'multimedia/sprites/traseras/69.gif', 'multimedia/sonidos/cries_pokemon_legacy_69.ogg', 1, 'PLANTA', 'VENENO'),
(70, 'WEEPINBELL', 'multimedia/imagenes/delanteras/70.png', 'multimedia/imagenes/traseras/70.png', 'multimedia/sprites/delanteras/70.gif', 'multimedia/sprites/traseras/70.gif', 'multimedia/sonidos/cries_pokemon_legacy_70.ogg', 2, 'PLANTA', 'VENENO'),
(71, 'VICTREEBEL', 'multimedia/imagenes/delanteras/71.png', 'multimedia/imagenes/traseras/71.png', 'multimedia/sprites/delanteras/71.gif', 'multimedia/sprites/traseras/71.gif', 'multimedia/sonidos/cries_pokemon_legacy_71.ogg', 3, 'PLANTA', 'VENENO'),
(72, 'TENTACOOL', 'multimedia/imagenes/delanteras/72.png', 'multimedia/imagenes/traseras/72.png', 'multimedia/sprites/delanteras/72.gif', 'multimedia/sprites/traseras/72.gif', 'multimedia/sonidos/cries_pokemon_legacy_72.ogg', 1, 'AGUA', 'VENENO'),
(73, 'TENTACRUEL', 'multimedia/imagenes/delanteras/73.png', 'multimedia/imagenes/traseras/73.png', 'multimedia/sprites/delanteras/73.gif', 'multimedia/sprites/traseras/73.gif', 'multimedia/sonidos/cries_pokemon_legacy_73.ogg', 2, 'AGUA', 'VENENO'),
(74, 'GEODUDE', 'multimedia/imagenes/delanteras/74.png', 'multimedia/imagenes/traseras/74.png', 'multimedia/sprites/delanteras/74.gif', 'multimedia/sprites/traseras/74.gif', 'multimedia/sonidos/cries_pokemon_legacy_74.ogg', 1, 'ROCA', 'TIERRA'),
(75, 'GRAVELER', 'multimedia/imagenes/delanteras/75.png', 'multimedia/imagenes/traseras/75.png', 'multimedia/sprites/delanteras/75.gif', 'multimedia/sprites/traseras/75.gif', 'multimedia/sonidos/cries_pokemon_legacy_75.ogg', 2, 'ROCA', 'TIERRA'),
(76, 'GOLEM', 'multimedia/imagenes/delanteras/76.png', 'multimedia/imagenes/traseras/76.png', 'multimedia/sprites/delanteras/76.gif', 'multimedia/sprites/traseras/76.gif', 'multimedia/sonidos/cries_pokemon_legacy_76.ogg', 3, 'ROCA', 'TIERRA'),
(77, 'PONYTA', 'multimedia/imagenes/delanteras/77.png', 'multimedia/imagenes/traseras/77.png', 'multimedia/sprites/delanteras/77.gif', 'multimedia/sprites/traseras/77.gif', 'multimedia/sonidos/cries_pokemon_legacy_77.ogg', 1, 'FUEGO', NULL),
(78, 'RAPIDASH', 'multimedia/imagenes/delanteras/78.png', 'multimedia/imagenes/traseras/78.png', 'multimedia/sprites/delanteras/78.gif', 'multimedia/sprites/traseras/78.gif', 'multimedia/sonidos/cries_pokemon_legacy_78.ogg', 2, 'FUEGO', NULL),
(79, 'SLOWPOKE', 'multimedia/imagenes/delanteras/79.png', 'multimedia/imagenes/traseras/79.png', 'multimedia/sprites/delanteras/79.gif', 'multimedia/sprites/traseras/79.gif', 'multimedia/sonidos/cries_pokemon_legacy_79.ogg', 1, 'AGUA', 'PSÍQUICO'),
(80, 'SLOWBRO', 'multimedia/imagenes/delanteras/80.png', 'multimedia/imagenes/traseras/80.png', 'multimedia/sprites/delanteras/80.gif', 'multimedia/sprites/traseras/80.gif', 'multimedia/sonidos/cries_pokemon_legacy_80.ogg', 2, 'AGUA', 'PSÍQUICO'),
(81, 'MAGNEMITE', 'multimedia/imagenes/delanteras/81.png', 'multimedia/imagenes/traseras/81.png', 'multimedia/sprites/delanteras/81.gif', 'multimedia/sprites/traseras/81.gif', 'multimedia/sonidos/cries_pokemon_legacy_81.ogg', 1, 'ELÉCTRICO', NULL),
(82, 'MAGNETON', 'multimedia/imagenes/delanteras/82.png', 'multimedia/imagenes/traseras/82.png', 'multimedia/sprites/delanteras/82.gif', 'multimedia/sprites/traseras/82.gif', 'multimedia/sonidos/cries_pokemon_legacy_82.ogg', 2, 'ELÉCTRICO', NULL),
(83, 'FARFETCH’D', 'multimedia/imagenes/delanteras/83.png', 'multimedia/imagenes/traseras/83.png', 'multimedia/sprites/delanteras/83.gif', 'multimedia/sprites/traseras/83.gif', 'multimedia/sonidos/cries_pokemon_legacy_83.ogg', 1, 'NORMAL', 'VOLADOR'),
(84, 'DODUO', 'multimedia/imagenes/delanteras/84.png', 'multimedia/imagenes/traseras/84.png', 'multimedia/sprites/delanteras/84.gif', 'multimedia/sprites/traseras/84.gif', 'multimedia/sonidos/cries_pokemon_legacy_84.ogg', 1, 'NORMAL', 'VOLADOR'),
(85, 'DODRIO', 'multimedia/imagenes/delanteras/85.png', 'multimedia/imagenes/traseras/85.png', 'multimedia/sprites/delanteras/85.gif', 'multimedia/sprites/traseras/85.gif', 'multimedia/sonidos/cries_pokemon_legacy_85.ogg', 2, 'NORMAL', 'VOLADOR'),
(86, 'SEEL', 'multimedia/imagenes/delanteras/86.png', 'multimedia/imagenes/traseras/86.png', 'multimedia/sprites/delanteras/86.gif', 'multimedia/sprites/traseras/86.gif', 'multimedia/sonidos/cries_pokemon_legacy_86.ogg', 1, 'AGUA', NULL),
(87, 'DEWGONG', 'multimedia/imagenes/delanteras/87.png', 'multimedia/imagenes/traseras/87.png', 'multimedia/sprites/delanteras/87.gif', 'multimedia/sprites/traseras/87.gif', 'multimedia/sonidos/cries_pokemon_legacy_87.ogg', 2, 'AGUA', 'HIELO'),
(88, 'GRIMER', 'multimedia/imagenes/delanteras/88.png', 'multimedia/imagenes/traseras/88.png', 'multimedia/sprites/delanteras/88.gif', 'multimedia/sprites/traseras/88.gif', 'multimedia/sonidos/cries_pokemon_legacy_88.ogg', 1, 'VENENO', NULL),
(89, 'MUK', 'multimedia/imagenes/delanteras/89.png', 'multimedia/imagenes/traseras/89.png', 'multimedia/sprites/delanteras/89.gif', 'multimedia/sprites/traseras/89.gif', 'multimedia/sonidos/cries_pokemon_legacy_89.ogg', 2, 'VENENO', NULL),
(90, 'SHELLDER', 'multimedia/imagenes/delanteras/90.png', 'multimedia/imagenes/traseras/90.png', 'multimedia/sprites/delanteras/90.gif', 'multimedia/sprites/traseras/90.gif', 'multimedia/sonidos/cries_pokemon_legacy_90.ogg', 1, 'AGUA', NULL),
(91, 'CLOYSTER', 'multimedia/imagenes/delanteras/91.png', 'multimedia/imagenes/traseras/91.png', 'multimedia/sprites/delanteras/91.gif', 'multimedia/sprites/traseras/91.gif', 'multimedia/sonidos/cries_pokemon_legacy_91.ogg', 2, 'AGUA', 'HIELO'),
(92, 'GASTLY', 'multimedia/imagenes/delanteras/92.png', 'multimedia/imagenes/traseras/92.png', 'multimedia/sprites/delanteras/92.gif', 'multimedia/sprites/traseras/92.gif', 'multimedia/sonidos/cries_pokemon_legacy_92.ogg', 1, 'FANTASMA', 'VENENO'),
(93, 'HAUNTER', 'multimedia/imagenes/delanteras/93.png', 'multimedia/imagenes/traseras/93.png', 'multimedia/sprites/delanteras/93.gif', 'multimedia/sprites/traseras/93.gif', 'multimedia/sonidos/cries_pokemon_legacy_93.ogg', 2, 'FANTASMA', 'VENENO'),
(94, 'GENGAR', 'multimedia/imagenes/delanteras/94.png', 'multimedia/imagenes/traseras/94.png', 'multimedia/sprites/delanteras/94.gif', 'multimedia/sprites/traseras/94.gif', 'multimedia/sonidos/cries_pokemon_legacy_94.ogg', 3, 'FANTASMA', 'VENENO'),
(95, 'ONIX', 'multimedia/imagenes/delanteras/95.png', 'multimedia/imagenes/traseras/95.png', 'multimedia/sprites/delanteras/95.gif', 'multimedia/sprites/traseras/95.gif', 'multimedia/sonidos/cries_pokemon_legacy_95.ogg', 1, 'ROCA', 'TIERRA'),
(96, 'DROWZEE', 'multimedia/imagenes/delanteras/96.png', 'multimedia/imagenes/traseras/96.png', 'multimedia/sprites/delanteras/96.gif', 'multimedia/sprites/traseras/96.gif', 'multimedia/sonidos/cries_pokemon_legacy_96.ogg', 1, 'PSÍQUICO', NULL),
(97, 'HYPNO', 'multimedia/imagenes/delanteras/97.png', 'multimedia/imagenes/traseras/97.png', 'multimedia/sprites/delanteras/97.gif', 'multimedia/sprites/traseras/97.gif', 'multimedia/sonidos/cries_pokemon_legacy_97.ogg', 2, 'PSÍQUICO', NULL),
(98, 'KRABBY', 'multimedia/imagenes/delanteras/98.png', 'multimedia/imagenes/traseras/98.png', 'multimedia/sprites/delanteras/98.gif', 'multimedia/sprites/traseras/98.gif', 'multimedia/sonidos/cries_pokemon_legacy_98.ogg', 1, 'AGUA', NULL),
(99, 'KINGLER', 'multimedia/imagenes/delanteras/99.png', 'multimedia/imagenes/traseras/99.png', 'multimedia/sprites/delanteras/99.gif', 'multimedia/sprites/traseras/99.gif', 'multimedia/sonidos/cries_pokemon_legacy_99.ogg', 2, 'AGUA', NULL),
(100, 'VOLTORB', 'multimedia/imagenes/delanteras/100.png', 'multimedia/imagenes/traseras/100.png', 'multimedia/sprites/delanteras/100.gif', 'multimedia/sprites/traseras/100.gif', 'multimedia/sonidos/cries_pokemon_legacy_100.ogg', 1, 'ELÉCTRICO', NULL),
(101, 'ELECTRODE', 'multimedia/imagenes/delanteras/101.png', 'multimedia/imagenes/traseras/101.png', 'multimedia/sprites/delanteras/101.gif', 'multimedia/sprites/traseras/101.gif', 'multimedia/sonidos/cries_pokemon_legacy_101.ogg', 2, 'ELÉCTRICO', NULL),
(102, 'EXEGGCUTE', 'multimedia/imagenes/delanteras/102.png', 'multimedia/imagenes/traseras/102.png', 'multimedia/sprites/delanteras/102.gif', 'multimedia/sprites/traseras/102.gif', 'multimedia/sonidos/cries_pokemon_legacy_102.ogg', 1, 'PLANTA', 'PSÍQUICO'),
(103, 'EXEGGUTOR', 'multimedia/imagenes/delanteras/103.png', 'multimedia/imagenes/traseras/103.png', 'multimedia/sprites/delanteras/103.gif', 'multimedia/sprites/traseras/103.gif', 'multimedia/sonidos/cries_pokemon_legacy_103.ogg', 2, 'PLANTA', 'PSÍQUICO'),
(104, 'CUBONE', 'multimedia/imagenes/delanteras/104.png', 'multimedia/imagenes/traseras/104.png', 'multimedia/sprites/delanteras/104.gif', 'multimedia/sprites/traseras/104.gif', 'multimedia/sonidos/cries_pokemon_legacy_104.ogg', 1, 'TIERRA', NULL),
(105, 'MAROWAK', 'multimedia/imagenes/delanteras/105.png', 'multimedia/imagenes/traseras/105.png', 'multimedia/sprites/delanteras/105.gif', 'multimedia/sprites/traseras/105.gif', 'multimedia/sonidos/cries_pokemon_legacy_105.ogg', 2, 'TIERRA', NULL),
(106, 'HITMONLEE', 'multimedia/imagenes/delanteras/106.png', 'multimedia/imagenes/traseras/106.png', 'multimedia/sprites/delanteras/106.gif', 'multimedia/sprites/traseras/106.gif', 'multimedia/sonidos/cries_pokemon_legacy_106.ogg', 1, 'LUCHA', NULL),
(107, 'HITMONCHAN', 'multimedia/imagenes/delanteras/107.png', 'multimedia/imagenes/traseras/107.png', 'multimedia/sprites/delanteras/107.gif', 'multimedia/sprites/traseras/107.gif', 'multimedia/sonidos/cries_pokemon_legacy_107.ogg', 1, 'LUCHA', NULL),
(108, 'LICKITUNG', 'multimedia/imagenes/delanteras/108.png', 'multimedia/imagenes/traseras/108.png', 'multimedia/sprites/delanteras/108.gif', 'multimedia/sprites/traseras/108.gif', 'multimedia/sonidos/cries_pokemon_legacy_108.ogg', 1, 'NORMAL', NULL),
(109, 'KOFFING', 'multimedia/imagenes/delanteras/109.png', 'multimedia/imagenes/traseras/109.png', 'multimedia/sprites/delanteras/109.gif', 'multimedia/sprites/traseras/109.gif', 'multimedia/sonidos/cries_pokemon_legacy_109.ogg', 1, 'VENENO', NULL),
(110, 'WEEZING', 'multimedia/imagenes/delanteras/110.png', 'multimedia/imagenes/traseras/110.png', 'multimedia/sprites/delanteras/110.gif', 'multimedia/sprites/traseras/110.gif', 'multimedia/sonidos/cries_pokemon_legacy_110.ogg', 2, 'VENENO', NULL),
(111, 'RHYHORN', 'multimedia/imagenes/delanteras/111.png', 'multimedia/imagenes/traseras/111.png', 'multimedia/sprites/delanteras/111.gif', 'multimedia/sprites/traseras/111.gif', 'multimedia/sonidos/cries_pokemon_legacy_111.ogg', 1, 'TIERRA', 'ROCA'),
(112, 'RHYDON', 'multimedia/imagenes/delanteras/112.png', 'multimedia/imagenes/traseras/112.png', 'multimedia/sprites/delanteras/112.gif', 'multimedia/sprites/traseras/112.gif', 'multimedia/sonidos/cries_pokemon_legacy_112.ogg', 2, 'TIERRA', 'ROCA'),
(113, 'CHANSEY', 'multimedia/imagenes/delanteras/113.png', 'multimedia/imagenes/traseras/113.png', 'multimedia/sprites/delanteras/113.gif', 'multimedia/sprites/traseras/113.gif', 'multimedia/sonidos/cries_pokemon_legacy_113.ogg', 1, 'NORMAL', NULL),
(114, 'TANGELA', 'multimedia/imagenes/delanteras/114.png', 'multimedia/imagenes/traseras/114.png', 'multimedia/sprites/delanteras/114.gif', 'multimedia/sprites/traseras/114.gif', 'multimedia/sonidos/cries_pokemon_legacy_114.ogg', 1, 'PLANTA', NULL),
(115, 'KANGASKHAN', 'multimedia/imagenes/delanteras/115.png', 'multimedia/imagenes/traseras/115.png', 'multimedia/sprites/delanteras/115.gif', 'multimedia/sprites/traseras/115.gif', 'multimedia/sonidos/cries_pokemon_legacy_115.ogg', 1, 'NORMAL', NULL),
(116, 'HORSEA', 'multimedia/imagenes/delanteras/116.png', 'multimedia/imagenes/traseras/116.png', 'multimedia/sprites/delanteras/116.gif', 'multimedia/sprites/traseras/116.gif', 'multimedia/sonidos/cries_pokemon_legacy_116.ogg', 1, 'AGUA', NULL),
(117, 'SEADRA', 'multimedia/imagenes/delanteras/117.png', 'multimedia/imagenes/traseras/117.png', 'multimedia/sprites/delanteras/117.gif', 'multimedia/sprites/traseras/117.gif', 'multimedia/sonidos/cries_pokemon_legacy_117.ogg', 2, 'AGUA', NULL),
(118, 'GOLDEEN', 'multimedia/imagenes/delanteras/118.png', 'multimedia/imagenes/traseras/118.png', 'multimedia/sprites/delanteras/118.gif', 'multimedia/sprites/traseras/118.gif', 'multimedia/sonidos/cries_pokemon_legacy_118.ogg', 1, 'AGUA', NULL),
(119, 'SEAKING', 'multimedia/imagenes/delanteras/119.png', 'multimedia/imagenes/traseras/119.png', 'multimedia/sprites/delanteras/119.gif', 'multimedia/sprites/traseras/119.gif', 'multimedia/sonidos/cries_pokemon_legacy_119.ogg', 2, 'AGUA', NULL),
(120, 'STARYU', 'multimedia/imagenes/delanteras/120.png', 'multimedia/imagenes/traseras/120.png', 'multimedia/sprites/delanteras/120.gif', 'multimedia/sprites/traseras/120.gif', 'multimedia/sonidos/cries_pokemon_legacy_120.ogg', 1, 'AGUA', NULL),
(121, 'STARMIE', 'multimedia/imagenes/delanteras/121.png', 'multimedia/imagenes/traseras/121.png', 'multimedia/sprites/delanteras/121.gif', 'multimedia/sprites/traseras/121.gif', 'multimedia/sonidos/cries_pokemon_legacy_121.ogg', 2, 'AGUA', 'PSÍQUICO'),
(122, 'MR. MIME', 'multimedia/imagenes/delanteras/122.png', 'multimedia/imagenes/traseras/122.png', 'multimedia/sprites/delanteras/122.gif', 'multimedia/sprites/traseras/122.gif', 'multimedia/sonidos/cries_pokemon_legacy_122.ogg', 1, 'PSÍQUICO', 'HADA'),
(123, 'SCYTHER', 'multimedia/imagenes/delanteras/123.png', 'multimedia/imagenes/traseras/123.png', 'multimedia/sprites/delanteras/123.gif', 'multimedia/sprites/traseras/123.gif', 'multimedia/sonidos/cries_pokemon_legacy_123.ogg', 1, 'BICHO', 'VOLADOR'),
(124, 'JYNX', 'multimedia/imagenes/delanteras/124.png', 'multimedia/imagenes/traseras/124.png', 'multimedia/sprites/delanteras/124.gif', 'multimedia/sprites/traseras/124.gif', 'multimedia/sonidos/cries_pokemon_legacy_124.ogg', 1, 'HIELO', 'PSÍQUICO'),
(125, 'ELECTABUZZ', 'multimedia/imagenes/delanteras/125.png', 'multimedia/imagenes/traseras/125.png', 'multimedia/sprites/delanteras/125.gif', 'multimedia/sprites/traseras/125.gif', 'multimedia/sonidos/cries_pokemon_legacy_125.ogg', 1, 'ELÉCTRICO', NULL),
(126, 'MAGMAR', 'multimedia/imagenes/delanteras/126.png', 'multimedia/imagenes/traseras/126.png', 'multimedia/sprites/delanteras/126.gif', 'multimedia/sprites/traseras/126.gif', 'multimedia/sonidos/cries_pokemon_legacy_126.ogg', 1, 'FUEGO', NULL),
(127, 'PINSIR', 'multimedia/imagenes/delanteras/127.png', 'multimedia/imagenes/traseras/127.png', 'multimedia/sprites/delanteras/127.gif', 'multimedia/sprites/traseras/127.gif', 'multimedia/sonidos/cries_pokemon_legacy_127.ogg', 1, 'BICHO', NULL),
(128, 'TAUROS', 'multimedia/imagenes/delanteras/128.png', 'multimedia/imagenes/traseras/128.png', 'multimedia/sprites/delanteras/128.gif', 'multimedia/sprites/traseras/128.gif', 'multimedia/sonidos/cries_pokemon_legacy_128.ogg', 1, 'NORMAL', NULL),
(129, 'MAGIKARP', 'multimedia/imagenes/delanteras/129.png', 'multimedia/imagenes/traseras/129.png', 'multimedia/sprites/delanteras/129.gif', 'multimedia/sprites/traseras/129.gif', 'multimedia/sonidos/cries_pokemon_legacy_129.ogg', 1, 'AGUA', NULL),
(130, 'GYARADOS', 'multimedia/imagenes/delanteras/130.png', 'multimedia/imagenes/traseras/130.png', 'multimedia/sprites/delanteras/130.gif', 'multimedia/sprites/traseras/130.gif', 'multimedia/sonidos/cries_pokemon_legacy_130.ogg', 2, 'AGUA', 'VOLADOR'),
(131, 'LAPRAS', 'multimedia/imagenes/delanteras/131.png', 'multimedia/imagenes/traseras/131.png', 'multimedia/sprites/delanteras/131.gif', 'multimedia/sprites/traseras/131.gif', 'multimedia/sonidos/cries_pokemon_legacy_131.ogg', 1, 'AGUA', 'HIELO'),
(132, 'DITTO', 'multimedia/imagenes/delanteras/132.png', 'multimedia/imagenes/traseras/132.png', 'multimedia/sprites/delanteras/132.gif', 'multimedia/sprites/traseras/132.gif', 'multimedia/sonidos/cries_pokemon_legacy_132.ogg', 1, 'NORMAL', NULL),
(133, 'EEVEE', 'multimedia/imagenes/delanteras/133.png', 'multimedia/imagenes/traseras/133.png', 'multimedia/sprites/delanteras/133.gif', 'multimedia/sprites/traseras/133.gif', 'multimedia/sonidos/cries_pokemon_legacy_133.ogg', 1, 'NORMAL', NULL),
(134, 'VAPOREON', 'multimedia/imagenes/delanteras/134.png', 'multimedia/imagenes/traseras/134.png', 'multimedia/sprites/delanteras/134.gif', 'multimedia/sprites/traseras/134.gif', 'multimedia/sonidos/cries_pokemon_legacy_134.ogg', 2, 'AGUA', NULL),
(135, 'JOLTEON', 'multimedia/imagenes/delanteras/135.png', 'multimedia/imagenes/traseras/135.png', 'multimedia/sprites/delanteras/135.gif', 'multimedia/sprites/traseras/135.gif', 'multimedia/sonidos/cries_pokemon_legacy_135.ogg', 2, 'ELÉCTRICO', NULL),
(136, 'FLAREON', 'multimedia/imagenes/delanteras/136.png', 'multimedia/imagenes/traseras/136.png', 'multimedia/sprites/delanteras/136.gif', 'multimedia/sprites/traseras/136.gif', 'multimedia/sonidos/cries_pokemon_legacy_136.ogg', 2, 'FUEGO', NULL),
(137, 'PORYGON', 'multimedia/imagenes/delanteras/137.png', 'multimedia/imagenes/traseras/137.png', 'multimedia/sprites/delanteras/137.gif', 'multimedia/sprites/traseras/137.gif', 'multimedia/sonidos/cries_pokemon_legacy_137.ogg', 1, 'NORMAL', NULL),
(138, 'OMANYTE', 'multimedia/imagenes/delanteras/138.png', 'multimedia/imagenes/traseras/138.png', 'multimedia/sprites/delanteras/138.gif', 'multimedia/sprites/traseras/138.gif', 'multimedia/sonidos/cries_pokemon_legacy_138.ogg', 1, 'ROCA', 'AGUA'),
(139, 'OMASTAR', 'multimedia/imagenes/delanteras/139.png', 'multimedia/imagenes/traseras/139.png', 'multimedia/sprites/delanteras/139.gif', 'multimedia/sprites/traseras/139.gif', 'multimedia/sonidos/cries_pokemon_legacy_139.ogg', 2, 'ROCA', 'AGUA'),
(140, 'KABUTO', 'multimedia/imagenes/delanteras/140.png', 'multimedia/imagenes/traseras/140.png', 'multimedia/sprites/delanteras/140.gif', 'multimedia/sprites/traseras/140.gif', 'multimedia/sonidos/cries_pokemon_legacy_140.ogg', 1, 'ROCA', 'AGUA'),
(141, 'KABUTOPS', 'multimedia/imagenes/delanteras/141.png', 'multimedia/imagenes/traseras/141.png', 'multimedia/sprites/delanteras/141.gif', 'multimedia/sprites/traseras/141.gif', 'multimedia/sonidos/cries_pokemon_legacy_141.ogg', 2, 'ROCA', 'AGUA'),
(142, 'AERODACTYL', 'multimedia/imagenes/delanteras/142.png', 'multimedia/imagenes/traseras/142.png', 'multimedia/sprites/delanteras/142.gif', 'multimedia/sprites/traseras/142.gif', 'multimedia/sonidos/cries_pokemon_legacy_142.ogg', 1, 'ROCA', 'VOLADOR'),
(143, 'SNORLAX', 'multimedia/imagenes/delanteras/143.png', 'multimedia/imagenes/traseras/143.png', 'multimedia/sprites/delanteras/143.gif', 'multimedia/sprites/traseras/143.gif', 'multimedia/sonidos/cries_pokemon_legacy_143.ogg', 1, 'NORMAL', NULL),
(144, 'ARTICUNO', 'multimedia/imagenes/delanteras/144.png', 'multimedia/imagenes/traseras/144.png', 'multimedia/sprites/delanteras/144.gif', 'multimedia/sprites/traseras/144.gif', 'multimedia/sonidos/cries_pokemon_legacy_144.ogg', 1, 'HIELO', 'VOLADOR'),
(145, 'ZAPDOS', 'multimedia/imagenes/delanteras/145.png', 'multimedia/imagenes/traseras/145.png', 'multimedia/sprites/delanteras/145.gif', 'multimedia/sprites/traseras/145.gif', 'multimedia/sonidos/cries_pokemon_legacy_145.ogg', 1, 'ELÉCTRICO', 'VOLADOR'),
(146, 'MOLTRES', 'multimedia/imagenes/delanteras/146.png', 'multimedia/imagenes/traseras/146.png', 'multimedia/sprites/delanteras/146.gif', 'multimedia/sprites/traseras/146.gif', 'multimedia/sonidos/cries_pokemon_legacy_146.ogg', 1, 'FUEGO', 'VOLADOR'),
(147, 'DRATINI', 'multimedia/imagenes/delanteras/147.png', 'multimedia/imagenes/traseras/147.png', 'multimedia/sprites/delanteras/147.gif', 'multimedia/sprites/traseras/147.gif', 'multimedia/sonidos/cries_pokemon_legacy_147.ogg', 1, 'DRAGÓN', NULL),
(148, 'DRAGONAIR', 'multimedia/imagenes/delanteras/148.png', 'multimedia/imagenes/traseras/148.png', 'multimedia/sprites/delanteras/148.gif', 'multimedia/sprites/traseras/148.gif', 'multimedia/sonidos/cries_pokemon_legacy_148.ogg', 2, 'DRAGÓN', NULL),
(149, 'DRAGONITE', 'multimedia/imagenes/delanteras/149.png', 'multimedia/imagenes/traseras/149.png', 'multimedia/sprites/delanteras/149.gif', 'multimedia/sprites/traseras/149.gif', 'multimedia/sonidos/cries_pokemon_legacy_149.ogg', 3, 'DRAGÓN', 'VOLADOR'),
(150, 'MEWTWO', 'multimedia/imagenes/delanteras/150.png', 'multimedia/imagenes/traseras/150.png', 'multimedia/sprites/delanteras/150.gif', 'multimedia/sprites/traseras/150.gif', 'multimedia/sonidos/cries_pokemon_legacy_150.ogg', 1, 'PSÍQUICO', NULL),
(151, 'MEW', 'multimedia/imagenes/delanteras/151.png', 'multimedia/imagenes/traseras/151.png', 'multimedia/sprites/delanteras/151.gif', 'multimedia/sprites/traseras/151.gif', 'multimedia/sonidos/cries_pokemon_legacy_151.ogg', 1, 'PSÍQUICO', NULL);

-- Insert OBJETO
INSERT INTO OBJETO( ID_OBJETO , NOM_OBJETO , ATAQUE , DEFENSA ,AT_ESPECIAL , DEF_ESPECIAL , VELOCIDAD , VITALIDAD , PP , PRECIO) VALUES 
(001, 'Pesa', 20 , 20 , 0 , 0 , -20 , 0 , 0 , 200),
(002, 'Pluma', 0 , -20 , 0 , -20 , 30 , 0 , 0 , 500),
(003, 'Chaleco', -15 , 20 , 0 , 20 , -15 , 0 , 0 , 1000),
(004, 'Bastón', 0 , 0 , 0 , 0 , -15 , 0 , 20 , 750),
(005, 'Pilas', 0 , 0 , 0 , -30 , 0 , 0 , 50 , 100),
(006, 'Eter', 0 , 0 , 0 , 0 , 0 , 0 , 40 , 300),
(007, 'Anillo unico', 10 , 0 , 0 , 0 , 0 , 0 , 0 , 5000),
(008, 'Pokeball', 0 , 0 , 0 , 0 , 0 , 0 , 0 , 50),
(009, 'Pocion', 0 , 0 , 0 , 0 , 0 , 30 , 0 , 600),
(010, 'Superpocion', 0 , 0 , 0 , 0 , 0 , 60 , 0 , 800),
(011, 'Hiperpocion', 0 , 0 , 0 , 0 , 0 , 90 , 0 , 2000);